In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('/opt/data/secc/secc_state_name_age_sex_social_cat.csv.gz', usecols=['state'])

In [2]:
df.size

420613593

In [3]:
df.groupby(['state']).size()

state
arunachal pradesh     1189638
assam                 7114232
bihar                54197114
chhattisgarh          8536248
gujarat              20474063
haryana               7928621
kerala               17805905
madhya pradesh       33788308
maharashtra          41188662
mizoram                120572
nagaland               854973
odisha               31567430
punjab                8848364
rajasthan            28359145
sikkim                 266484
tamilnadu            30675056
uttar pradesh        74437606
uttarakhand           4425566
west bengal          48835606
dtype: int64

In [4]:
df = pd.read_csv('/opt/data/secc/secc_state_name_age_sex_social_cat.csv.gz', usecols=['state', 'name', 'social_cat'])
df

                       state social_cat                    name
0          arunachal pradesh         st               jaflo mai
1          arunachal pradesh         st           jingroso tega
2          arunachal pradesh         st            thankha tega
3          arunachal pradesh         st             yatong tega
4          arunachal pradesh         st               bijoy mai
5          arunachal pradesh         st           dimongso tega
6          arunachal pradesh         st         grotho tabronyu
7          arunachal pradesh         st            kaflulum mai
8          arunachal pradesh         st          kamlingso tega
9          arunachal pradesh         st             namkho tega
10         arunachal pradesh         st                  r_tega
11         arunachal pradesh         st        talelum tabronyu
12         arunachal pradesh         st               jaflo mai
13         arunachal pradesh         st           jingroso tega
14         arunachal pradesh         st            thankha tega
15         arunachal pradesh         st             yatong tega
16         arunachal pradesh         st               bijoy mai
17         arunachal pradesh         st           dimongso tega
18         arunachal pradesh         st         grotho tabronyu
19         arunachal pradesh         st            kaflulum mai
20         arunachal pradesh         st          kamlingso tega
21         arunachal pradesh         st             namkho tega
22         arunachal pradesh         st                  r_tega
23         arunachal pradesh         st        talelum tabronyu
24         arunachal pradesh         st               jaflo mai
25         arunachal pradesh         st           jingroso tega
26         arunachal pradesh         st            thankha tega
27         arunachal pradesh         st             yatong tega
28         arunachal pradesh         st               bijoy mai
29         arunachal pradesh         st           dimongso tega
...                      ...        ...                     ...
420613563        west bengal         sc       ajit kumar mandal
420613564        west bengal         sc            ananta maity
420613565        west bengal         sc     ashish kumar mandal
420613566        west bengal         sc            chabi mandal
420613567        west bengal         sc      chittaranjan maity
420613568        west bengal         sc        debabrata mandal
420613569        west bengal         sc           dibakar maity
420613570        west bengal         sc              gour maity
420613571        west bengal         sc        hrishikesh maity
420613572        west bengal         sc             indra maity
420613573        west bengal         sc             jiten maity
420613574        west bengal         sc           kamlesh maity
420613575        west bengal         sc             malay maity
420613576        west bengal         sc             nitai maity
420613577        west bengal         sc      parameshwar mandal
420613578        west bengal         sc            pathik maity
420613579        west bengal      other  pranabananda mahapatra
420613580        west bengal         sc         pranatosh maity
420613581        west bengal         sc     pranay kumar mandal
420613582        west bengal         sc      pulin bihari maity
420613583        west bengal         sc      rabindranath hajra
420613584        west bengal         sc           rajesh  maity
420613585        west bengal         sc             saroj maity
420613586        west bengal         sc      satyanarayan maity
420613587        west bengal         sc          shatadal maity
420613588        west bengal         sc          sudhansu maity
420613589        west bengal         sc       sujay kumar maity
420613590        west bengal         sc          sushanta maity
420613591        west bengal      other       basanta mahapatra
420613592        west bengal      other        00004_devdas_das

[420613593 rows x 3 columns]

In [5]:
df.groupby(['social_cat']).size()

social_cat
other    297501016
sc        80649033
st        42463544
dtype: int64

In [6]:
df.describe()

                state social_cat       name
count       420613593  420613593  420566844
unique             19          3   43992290
top     uttar pradesh      other     ramesh
freq         74437606  297501016     552077