In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/opt/data/secc/secc_state_name_age_sex_social_cat_state0_9.csv.gz')
df

           state gender social_cat  birth_year      last_name
0              0      m          t        1979            mai
1              0      m          t        1986           tega
2              0      m          t        1954           tega
3              0      m          t        1964           tega
4              0      m          t        1984            mai
5              0      m          t        1952           tega
6              0      m          t        1979       tabronyu
7              0      m          t        1968            mai
8              0      m          t        1981           tega
9              0      m          t        1954           tega
10             0      m          t        1939           tega
11             0      m          t        1959       tabronyu
12             0      m          t        1979            mai
13             0      m          t        1986           tega
14             0      m          t        1954           tega
15             0      m          t        1964           tega
16             0      m          t        1984            mai
17             0      m          t        1952           tega
18             0      m          t        1979       tabronyu
19             0      m          t        1968            mai
20             0      m          t        1981           tega
21             0      m          t        1954           tega
22             0      m          t        1939           tega
23             0      m          t        1959       tabronyu
24             0      m          t        1979            mai
25             0      m          t        1986           tega
26             0      m          t        1954           tega
27             0      m          t        1964           tega
28             0      m          t        1984            mai
29             0      m          t        1952           tega
...          ...    ...        ...         ...            ...
198059326      9      f          t        1933            NaN
198059327      9      f          t        1936      tinthangi
198059328      9      m          t        1980    lalthazuala
198059329      9      m          t        1984    laldinsanga
198059330      9      m          t        1987     lalfakawma
198059331      9      m          t        1974   lalremthanga
198059332      9      m          t        1974    lalruatkima
198059333      9      m          t        1972     zodinmawia
198059334      9      m          t        1966            NaN
198059335      9      m          t        1976          muana
198059336      9      m          t        1960    vanlalmawia
198059337      9      m          t        1979     dawngliana
198059338      9      m          t        1979  lalrintluanga
198059339      9      m          t        1965            NaN
198059340      9      m          t        1975            NaN
198059341      9      f          t        1951            NaN
198059342      9      m          t        1972            NaN
198059343      9      m          t        1976            NaN
198059344      9      f          t        1951            NaN
198059345      9      m          t        1958     sangthanga
198059346      9      m          t        1983            NaN
198059347      9      f          t        1939            NaN
198059348      9      f          t        1942            NaN
198059349      9      m          t        2007            NaN
198059350      9      f          t        1949            NaN
198059351      9      f          t        1944            NaN
198059352      9      m          t        1960            NaN
198059353      9      m          t        1978            NaN
198059354      9      m          t        1957            NaN
198059355      9      f          t        1970            NaN

[198059356 rows x 5 columns]

In [3]:
df.dropna(subset=['last_name'], inplace=True)
df.drop(df[~df.last_name.str.contains('^[a-z]{2,}')].index, inplace=True)
df.drop(df[df.last_name.str.contains('\.')].index, inplace=True)
df

           state gender social_cat  birth_year      last_name
0              0      m          t        1979            mai
1              0      m          t        1986           tega
2              0      m          t        1954           tega
3              0      m          t        1964           tega
4              0      m          t        1984            mai
5              0      m          t        1952           tega
6              0      m          t        1979       tabronyu
7              0      m          t        1968            mai
8              0      m          t        1981           tega
9              0      m          t        1954           tega
10             0      m          t        1939           tega
11             0      m          t        1959       tabronyu
12             0      m          t        1979            mai
13             0      m          t        1986           tega
14             0      m          t        1954           tega
15             0      m          t        1964           tega
16             0      m          t        1984            mai
17             0      m          t        1952           tega
18             0      m          t        1979       tabronyu
19             0      m          t        1968            mai
20             0      m          t        1981           tega
21             0      m          t        1954           tega
22             0      m          t        1939           tega
23             0      m          t        1959       tabronyu
24             0      m          t        1979            mai
25             0      m          t        1986           tega
26             0      m          t        1954           tega
27             0      m          t        1964           tega
28             0      m          t        1984            mai
29             0      m          t        1952           tega
...          ...    ...        ...         ...            ...
198059269      9      f          t        1977  lalngaihzuali
198059270      9      m          t        1965     lalrindika
198059271      9      m          t        1987     lalrinkima
198059272      9      m          t        1970   ramdinthanga
198059273      9      m          t        1976  laldawngliana
198059274      9      m          t        1960     thangliana
198059275      9      m          t        1945     sangthanga
198059276      9      m          t        1953   zaneihthanga
198059278      9      m          t        1959    vanlalruata
198059279      9      m          t        1950     thamsaiama
198059280      9      m          t        1949     lianthanga
198059281      9      m          t        1971     lalawmpuia
198059282      9      m          t        1930      thamzuala
198059283      9      m          t        1948       sangkima
198059285      9      m          t        1975    lawmchhunga
198059292      9      m          t        1954          pautu
198059309      9      m          t        1982          bawla
198059320      9      m          t        1927          sailo
198059327      9      f          t        1936      tinthangi
198059328      9      m          t        1980    lalthazuala
198059329      9      m          t        1984    laldinsanga
198059330      9      m          t        1987     lalfakawma
198059331      9      m          t        1974   lalremthanga
198059332      9      m          t        1974    lalruatkima
198059333      9      m          t        1972     zodinmawia
198059335      9      m          t        1976          muana
198059336      9      m          t        1960    vanlalmawia
198059337      9      m          t        1979     dawngliana
198059338      9      m          t        1979  lalrintluanga
198059345      9      m          t        1958     sangthanga

[161378599 rows x 5 columns]

* i think it makes sense to only release data where count for last_name/first_name is > 100
* it will take out a bunch of weird names for now

In [4]:
adf = df[df['last_name'].groupby(df['last_name']).transform('size')>100]
adf

           state gender social_cat  birth_year   last_name
0              0      m          t        1979         mai
1              0      m          t        1986        tega
2              0      m          t        1954        tega
3              0      m          t        1964        tega
4              0      m          t        1984         mai
5              0      m          t        1952        tega
6              0      m          t        1979    tabronyu
7              0      m          t        1968         mai
8              0      m          t        1981        tega
9              0      m          t        1954        tega
10             0      m          t        1939        tega
11             0      m          t        1959    tabronyu
12             0      m          t        1979         mai
13             0      m          t        1986        tega
14             0      m          t        1954        tega
15             0      m          t        1964        tega
16             0      m          t        1984         mai
17             0      m          t        1952        tega
18             0      m          t        1979    tabronyu
19             0      m          t        1968         mai
20             0      m          t        1981        tega
21             0      m          t        1954        tega
22             0      m          t        1939        tega
23             0      m          t        1959    tabronyu
24             0      m          t        1979         mai
25             0      m          t        1986        tega
26             0      m          t        1954        tega
27             0      m          t        1964        tega
28             0      m          t        1984         mai
29             0      m          t        1952        tega
...          ...    ...        ...         ...         ...
198058416      9      m          t        1957       khuma
198058529      9      m          t        1975       sailo
198058603      9      m          t        1957       khuma
198058631      9      m          t        1961  laltanpuia
198058633      9      m          t        1955    malsawma
198058642      9      m          t        1963  lalrinawma
198058660      9      m          t        1975  lalrinawma
198058721      9      m          t        1965    malsawma
198058734      9      m          t        1958  laltanpuia
198058750      9      m          t        1967     cherian
198058771      9      m          t        1957   chaudhuri
198058830      9      m          t        1927       sailo
198058876      9      m          t        1961  laltanpuia
198058878      9      m          t        1955    malsawma
198058887      9      m          t        1963  lalrinawma
198058905      9      m          t        1975  lalrinawma
198058966      9      m          t        1965    malsawma
198058979      9      m          t        1958  laltanpuia
198058995      9      m          t        1967     cherian
198059016      9      m          t        1957   chaudhuri
198059075      9      m          t        1927       sailo
198059121      9      m          t        1961  laltanpuia
198059123      9      m          t        1955    malsawma
198059132      9      m          t        1963  lalrinawma
198059150      9      m          t        1975  lalrinawma
198059211      9      m          t        1965    malsawma
198059224      9      m          t        1958  laltanpuia
198059240      9      m          t        1967     cherian
198059261      9      m          t        1957   chaudhuri
198059320      9      m          t        1927       sailo

[151850715 rows x 5 columns]

In [5]:
adf['last_name'].groupby(adf['last_name']).size()

last_name
aaba          693
aabadar       141
aabaji        513
aabale        177
aabarao       153
aabas         105
aabasaheb     267
aabdin        183
aabhale       117
aabhare       213
aabid        1056
aabnave       129
aabu          114
aabuj         534
aachar        126
aachare       123
aachari       339
aachary       459
aacharya      783
aachre        195
aad           246
aadaga        228
aadagale      366
aadak         312
aadake        687
aadalinge     180
aadam         729
aadamane      204
aadambhai     240
aadasul       519
             ...
zoting        645
zoura         126
zubair        627
zuber         358
zugar         132
zugare       1584
zuge          189
zugre         237
zuhra         114
zujam         345
zulasana      135
zulasna       132
zumbar        268
zumman        114
zunaid        144
zungare       279
zunge         105
zunjar        189
zunjare       984
zunje         153
zunza         369
zunzare       153
zurade        231
zurale        324
zurange       216
zurde         132
zure          525
zurunge       192
zute          324
zyate         318
Name: last_name, Length: 55257, dtype: int64

In [6]:
gdf = adf.groupby(['state', 'birth_year', 'last_name']).agg({'gender': 'value_counts', 'social_cat': 'value_counts'}).unstack()

In [7]:
gdf

                   gender                    social_cat
                        c    f     m   o   t          c   f   m    o     t
0  1881 chakma        NaN  NaN   6.0 NaN NaN        NaN NaN NaN  6.0   NaN
        eke           NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1883 dui           NaN  6.0   NaN NaN NaN        NaN NaN NaN  NaN   6.0
        ete           NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
        kawa          NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1884 dagam         NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
        riba          NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1885 tabang        NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1887 raje          NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1888 ali           NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
        mossang       NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1889 singpho       NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1891 chandra       NaN  NaN   6.0 NaN NaN        NaN NaN NaN  6.0   NaN
        chotton       NaN  6.0   NaN NaN NaN        NaN NaN NaN  NaN   6.0
   1894 chakma        NaN  NaN   6.0 NaN NaN        NaN NaN NaN  6.0   NaN
   1895 bosumotari    NaN  6.0   NaN NaN NaN        NaN NaN NaN  6.0   NaN
        diru          NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1896 namati        NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1899 duri          NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1901 chader        NaN  6.0   NaN NaN NaN        NaN NaN NaN  NaN   6.0
        tamang        NaN  NaN   6.0 NaN NaN        NaN NaN NaN  6.0   NaN
        topu          NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1903 chakma        NaN  NaN   6.0 NaN NaN        NaN NaN NaN  6.0   NaN
        jamoh         NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
        tapok         NaN  6.0   NaN NaN NaN        NaN NaN NaN  NaN   6.0
        tatin         NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
   1904 bellai        NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
        ete           NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
        taggu         NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
        take          NaN  NaN   6.0 NaN NaN        NaN NaN NaN  NaN   6.0
...                   ...  ...   ...  ..  ..        ...  ..  ..  ...   ...
11 2010 pradhan       NaN  6.0   NaN NaN NaN        3.0 NaN NaN  NaN   3.0
        prusty        NaN  3.0   NaN NaN NaN        NaN NaN NaN  3.0   NaN
        ranjan        NaN  NaN   3.0 NaN NaN        NaN NaN NaN  3.0   NaN
        ray           NaN  NaN   3.0 NaN NaN        NaN NaN NaN  NaN   3.0
        rout          NaN  3.0   6.0 NaN NaN        NaN NaN NaN  9.0   NaN
        sabar         NaN  NaN   3.0 NaN NaN        NaN NaN NaN  NaN   3.0
        sahoo         NaN  NaN   3.0 NaN NaN        3.0 NaN NaN  NaN   NaN
        sahu          NaN  3.0   3.0 NaN NaN        NaN NaN NaN  6.0   NaN
        son           NaN  NaN   3.0 NaN NaN        NaN NaN NaN  NaN   3.0
        swani         NaN  3.0   NaN NaN NaN        NaN NaN NaN  3.0   NaN
        tarenia       NaN  NaN   3.0 NaN NaN        NaN NaN NaN  3.0   NaN
   2011 behera        NaN  NaN   3.0 NaN NaN        NaN NaN NaN  3.0   NaN
        das           NaN  NaN   3.0 NaN NaN        NaN NaN NaN  3.0   NaN
        digal         NaN  3.0   NaN NaN NaN        3.0 NaN NaN  NaN   NaN
        gagarai       NaN  NaN   3.0 NaN NaN        NaN NaN NaN  NaN   3.0
        giri          NaN  NaN   3.0 NaN NaN        NaN NaN NaN  3.0   NaN
        jena          NaN  3.0  12.0 NaN NaN        9.0 NaN NaN  6.0   NaN
        lenka         NaN  NaN   3.0 NaN NaN        NaN NaN NaN  3.0   NaN
        mahanta       NaN  3.0   NaN NaN NaN        NaN NaN NaN  3.0   NaN
        majhi         NaN  NaN   3.0 NaN NaN        NaN NaN NaN  NaN   3.0
        mohapatra     NaN  NaN   3.0 NaN NaN        NaN NaN NaN  3.0   NaN
        munda         NaN  NaN   3.0 NaN NaN        NaN NaN NaN  NaN   3.0
        nag           NaN  NaN   3.0 NaN NaN        NaN NaN NaN  NaN   3.0
        naik          NaN  NaN   3.0 NaN NaN        NaN NaN NaN  NaN   3.0
        parida        NaN  NaN   3.0 NaN NaN        NaN NaN NaN  3.0   NaN
        pradhan       NaN  9.0   3.0 NaN NaN        NaN NaN NaN  NaN  12.0
        rout          NaN  NaN   6.0 NaN NaN        NaN NaN NaN  6.0   NaN
        sahoo         NaN  NaN   3.0 NaN NaN        NaN NaN NaN  3.0   NaN
        samal         NaN  3.0   NaN NaN NaN        NaN NaN NaN  3.0   NaN
        sarakar       NaN  3.0   NaN NaN NaN        NaN NaN NaN  3.0   NaN

[3038863 rows x 10 columns]

In [8]:
gdf.reset_index(inplace=True)
gdf

        level_0 level_1     level_2 gender                    social_cat      \
                                         c    f     m   o   t          c   f
0             0    1881      chakma    NaN  NaN   6.0 NaN NaN        NaN NaN
1             0    1881         eke    NaN  NaN   6.0 NaN NaN        NaN NaN
2             0    1883         dui    NaN  6.0   NaN NaN NaN        NaN NaN
3             0    1883         ete    NaN  NaN   6.0 NaN NaN        NaN NaN
4             0    1883        kawa    NaN  NaN   6.0 NaN NaN        NaN NaN
5             0    1884       dagam    NaN  NaN   6.0 NaN NaN        NaN NaN
6             0    1884        riba    NaN  NaN   6.0 NaN NaN        NaN NaN
7             0    1885      tabang    NaN  NaN   6.0 NaN NaN        NaN NaN
8             0    1887        raje    NaN  NaN   6.0 NaN NaN        NaN NaN
9             0    1888         ali    NaN  NaN   6.0 NaN NaN        NaN NaN
10            0    1888     mossang    NaN  NaN   6.0 NaN NaN        NaN NaN
11            0    1889     singpho    NaN  NaN   6.0 NaN NaN        NaN NaN
12            0    1891     chandra    NaN  NaN   6.0 NaN NaN        NaN NaN
13            0    1891     chotton    NaN  6.0   NaN NaN NaN        NaN NaN
14            0    1894      chakma    NaN  NaN   6.0 NaN NaN        NaN NaN
15            0    1895  bosumotari    NaN  6.0   NaN NaN NaN        NaN NaN
16            0    1895        diru    NaN  NaN   6.0 NaN NaN        NaN NaN
17            0    1896      namati    NaN  NaN   6.0 NaN NaN        NaN NaN
18            0    1899        duri    NaN  NaN   6.0 NaN NaN        NaN NaN
19            0    1901      chader    NaN  6.0   NaN NaN NaN        NaN NaN
20            0    1901      tamang    NaN  NaN   6.0 NaN NaN        NaN NaN
21            0    1901        topu    NaN  NaN   6.0 NaN NaN        NaN NaN
22            0    1903      chakma    NaN  NaN   6.0 NaN NaN        NaN NaN
23            0    1903       jamoh    NaN  NaN   6.0 NaN NaN        NaN NaN
24            0    1903       tapok    NaN  6.0   NaN NaN NaN        NaN NaN
25            0    1903       tatin    NaN  NaN   6.0 NaN NaN        NaN NaN
26            0    1904      bellai    NaN  NaN   6.0 NaN NaN        NaN NaN
27            0    1904         ete    NaN  NaN   6.0 NaN NaN        NaN NaN
28            0    1904       taggu    NaN  NaN   6.0 NaN NaN        NaN NaN
29            0    1904        take    NaN  NaN   6.0 NaN NaN        NaN NaN
...         ...     ...         ...    ...  ...   ...  ..  ..        ...  ..
3038833      11    2010     pradhan    NaN  6.0   NaN NaN NaN        3.0 NaN
3038834      11    2010      prusty    NaN  3.0   NaN NaN NaN        NaN NaN
3038835      11    2010      ranjan    NaN  NaN   3.0 NaN NaN        NaN NaN
3038836      11    2010         ray    NaN  NaN   3.0 NaN NaN        NaN NaN
3038837      11    2010        rout    NaN  3.0   6.0 NaN NaN        NaN NaN
3038838      11    2010       sabar    NaN  NaN   3.0 NaN NaN        NaN NaN
3038839      11    2010       sahoo    NaN  NaN   3.0 NaN NaN        3.0 NaN
3038840      11    2010        sahu    NaN  3.0   3.0 NaN NaN        NaN NaN
3038841      11    2010         son    NaN  NaN   3.0 NaN NaN        NaN NaN
3038842      11    2010       swani    NaN  3.0   NaN NaN NaN        NaN NaN
3038843      11    2010     tarenia    NaN  NaN   3.0 NaN NaN        NaN NaN
3038844      11    2011      behera    NaN  NaN   3.0 NaN NaN        NaN NaN
3038845      11    2011         das    NaN  NaN   3.0 NaN NaN        NaN NaN
3038846      11    2011       digal    NaN  3.0   NaN NaN NaN        3.0 NaN
3038847      11    2011     gagarai    NaN  NaN   3.0 NaN NaN        NaN NaN
3038848      11    2011        giri    NaN  NaN   3.0 NaN NaN        NaN NaN
3038849      11    2011        jena    NaN  3.0  12.0 NaN NaN        9.0 NaN
3038850      11    2011       lenka    NaN  NaN   3.0 NaN NaN        NaN NaN
3038851      11    2011     mahanta    NaN  3.0   NaN NaN NaN        NaN NaN
3038852      11    2011       majhi    NaN  NaN   3.0 NaN NaN        NaN NaN
3038853      11    2011   mohapatra    NaN  NaN   3.0 NaN NaN        NaN NaN
3038854      11    2011       munda    NaN  NaN   3.0 NaN NaN        NaN NaN
3038855      11    2011         nag    NaN  NaN   3.0 NaN NaN        NaN NaN
3038856      11    2011        naik    NaN  NaN   3.0 NaN NaN        NaN NaN
3038857      11    2011      parida    NaN  NaN   3.0 NaN NaN        NaN NaN
3038858      11    2011     pradhan    NaN  9.0   3.0 NaN NaN        NaN NaN
3038859      11    2011        rout    NaN  NaN   6.0 NaN NaN        NaN NaN
3038860      11    2011       sahoo    NaN  NaN   3.0 NaN NaN        NaN NaN
3038861      11    2011       samal    NaN  3.0   NaN NaN NaN        NaN NaN
3038862      11    2011     sarakar    NaN  3.0   NaN NaN NaN        NaN NaN


          m    o     t
0       NaN  6.0   NaN
1       NaN  NaN   6.0
2       NaN  NaN   6.0
3       NaN  NaN   6.0
4       NaN  NaN   6.0
5       NaN  NaN   6.0
6       NaN  NaN   6.0
7       NaN  NaN   6.0
8       NaN  NaN   6.0
9       NaN  NaN   6.0
10      NaN  NaN   6.0
11      NaN  NaN   6.0
12      NaN  6.0   NaN
13      NaN  NaN   6.0
14      NaN  6.0   NaN
15      NaN  6.0   NaN
16      NaN  NaN   6.0
17      NaN  NaN   6.0
18      NaN  NaN   6.0
19      NaN  NaN   6.0
20      NaN  6.0   NaN
21      NaN  NaN   6.0
22      NaN  6.0   NaN
23      NaN  NaN   6.0
24      NaN  NaN   6.0
25      NaN  NaN   6.0
26      NaN  NaN   6.0
27      NaN  NaN   6.0
28      NaN  NaN   6.0
29      NaN  NaN   6.0
...      ..  ...   ...
3038833 NaN  NaN   3.0
3038834 NaN  3.0   NaN
3038835 NaN  3.0   NaN
3038836 NaN  NaN   3.0
3038837 NaN  9.0   NaN
3038838 NaN  NaN   3.0
3038839 NaN  NaN   NaN
3038840 NaN  6.0   NaN
3038841 NaN  NaN   3.0
3038842 NaN  3.0   NaN
3038843 NaN  3.0   NaN
3038844 NaN  3.0   NaN
3038845 NaN  3.0   NaN
3038846 NaN  NaN   NaN
3038847 NaN  NaN   3.0
3038848 NaN  3.0   NaN
3038849 NaN  6.0   NaN
3038850 NaN  3.0   NaN
3038851 NaN  3.0   NaN
3038852 NaN  NaN   3.0
3038853 NaN  3.0   NaN
3038854 NaN  NaN   3.0
3038855 NaN  NaN   3.0
3038856 NaN  NaN   3.0
3038857 NaN  3.0   NaN
3038858 NaN  NaN  12.0
3038859 NaN  6.0   NaN
3038860 NaN  3.0   NaN
3038861 NaN  3.0   NaN
3038862 NaN  3.0   NaN

[3038863 rows x 13 columns]

In [9]:
gdf.columns = ['_'.join(col).strip() for col in gdf.columns.values]
gdf

,level_0_,level_1_,level_2_,gender_c,gender_f,gender_m,gender_o,gender_t,social_cat_c,social_cat_f,social_cat_m,social_cat_o,social_cat_t
0,0,1881,chakma,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
1,0,1881,eke,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
2,0,1883,dui,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
3,0,1883,ete,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
4,0,1883,kawa,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
5,0,1884,dagam,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
6,0,1884,riba,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
7,0,1885,tabang,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
8,0,1887,raje,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
9,0,1888,ali,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
10,0,1888,mossang,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
11,0,1889,singpho,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
12,0,1891,chandra,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
13,0,1891,chotton,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
14,0,1894,chakma,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
15,0,1895,bosumotari,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN
16,0,1895,diru,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
17,0,1896,namati,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
18,0,1899,duri,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
19,0,1901,chader,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
20,0,1901,tamang,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
21,0,1901,topu,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
22,0,1903,chakma,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
23,0,1903,jamoh,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
24,0,1903,tapok,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
25,0,1903,tatin,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
26,0,1904,bellai,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
27,0,1904,ete,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
28,0,1904,taggu,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
29,0,1904,take,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3038833,11,2010,pradhan,NaN,6.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,3.0
3038834,11,2010,prusty,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038835,11,2010,ranjan,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038836,11,2010,ray,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3038837,11,2010,rout,NaN,3.0,6.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN
3038838,11,2010,sabar,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3038839,11,2010,sahoo,NaN,NaN,3.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN
3038840,11,2010,sahu,NaN,3.0,3.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
3038841,11,2010,son,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3038842,11,2010,swani,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038843,11,2010,tarenia,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038844,11,2011,behera,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038845,11,2011,das,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038846,11,2011,digal,NaN,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
3038847,11,2011,gagarai,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3038848,11,2011,giri,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038849,11,2011,jena,NaN,3.0,12.0,NaN,NaN,9.0,NaN,NaN,6.0,NaN
3038850,11,2011,lenka,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038851,11,2011,mahanta,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038852,11,2011,majhi,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3038853,11,2011,mohapatra,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038854,11,2011,munda,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3038855,11,2011,nag,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3038856,11,2011,naik,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3038857,11,2011,parida,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038858,11,2011,pradhan,NaN,9.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,12.0
3038859,11,2011,rout,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
3038860,11,2011,sahoo,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038861,11,2011,samal,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
3038862,11,2011,sarakar,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN

In [10]:
gdf = gdf[['level_0_', 'level_1_', 'level_2_', 'gender_m', 'gender_f', 'social_cat_c', 'social_cat_o', 'social_cat_t']]
gdf.columns = ['state', 'birth_year', 'last_name', 'n_male', 'n_female', 'n_sc', 'n_other', 'n_st']
gdf

         state  birth_year   last_name  n_male  n_female  n_sc  n_other  n_st
0            0        1881      chakma     6.0       NaN   NaN      6.0   NaN
1            0        1881         eke     6.0       NaN   NaN      NaN   6.0
2            0        1883         dui     NaN       6.0   NaN      NaN   6.0
3            0        1883         ete     6.0       NaN   NaN      NaN   6.0
4            0        1883        kawa     6.0       NaN   NaN      NaN   6.0
5            0        1884       dagam     6.0       NaN   NaN      NaN   6.0
6            0        1884        riba     6.0       NaN   NaN      NaN   6.0
7            0        1885      tabang     6.0       NaN   NaN      NaN   6.0
8            0        1887        raje     6.0       NaN   NaN      NaN   6.0
9            0        1888         ali     6.0       NaN   NaN      NaN   6.0
10           0        1888     mossang     6.0       NaN   NaN      NaN   6.0
11           0        1889     singpho     6.0       NaN   NaN      NaN   6.0
12           0        1891     chandra     6.0       NaN   NaN      6.0   NaN
13           0        1891     chotton     NaN       6.0   NaN      NaN   6.0
14           0        1894      chakma     6.0       NaN   NaN      6.0   NaN
15           0        1895  bosumotari     NaN       6.0   NaN      6.0   NaN
16           0        1895        diru     6.0       NaN   NaN      NaN   6.0
17           0        1896      namati     6.0       NaN   NaN      NaN   6.0
18           0        1899        duri     6.0       NaN   NaN      NaN   6.0
19           0        1901      chader     NaN       6.0   NaN      NaN   6.0
20           0        1901      tamang     6.0       NaN   NaN      6.0   NaN
21           0        1901        topu     6.0       NaN   NaN      NaN   6.0
22           0        1903      chakma     6.0       NaN   NaN      6.0   NaN
23           0        1903       jamoh     6.0       NaN   NaN      NaN   6.0
24           0        1903       tapok     NaN       6.0   NaN      NaN   6.0
25           0        1903       tatin     6.0       NaN   NaN      NaN   6.0
26           0        1904      bellai     6.0       NaN   NaN      NaN   6.0
27           0        1904         ete     6.0       NaN   NaN      NaN   6.0
28           0        1904       taggu     6.0       NaN   NaN      NaN   6.0
29           0        1904        take     6.0       NaN   NaN      NaN   6.0
...        ...         ...         ...     ...       ...   ...      ...   ...
3038833     11        2010     pradhan     NaN       6.0   3.0      NaN   3.0
3038834     11        2010      prusty     NaN       3.0   NaN      3.0   NaN
3038835     11        2010      ranjan     3.0       NaN   NaN      3.0   NaN
3038836     11        2010         ray     3.0       NaN   NaN      NaN   3.0
3038837     11        2010        rout     6.0       3.0   NaN      9.0   NaN
3038838     11        2010       sabar     3.0       NaN   NaN      NaN   3.0
3038839     11        2010       sahoo     3.0       NaN   3.0      NaN   NaN
3038840     11        2010        sahu     3.0       3.0   NaN      6.0   NaN
3038841     11        2010         son     3.0       NaN   NaN      NaN   3.0
3038842     11        2010       swani     NaN       3.0   NaN      3.0   NaN
3038843     11        2010     tarenia     3.0       NaN   NaN      3.0   NaN
3038844     11        2011      behera     3.0       NaN   NaN      3.0   NaN
3038845     11        2011         das     3.0       NaN   NaN      3.0   NaN
3038846     11        2011       digal     NaN       3.0   3.0      NaN   NaN
3038847     11        2011     gagarai     3.0       NaN   NaN      NaN   3.0
3038848     11        2011        giri     3.0       NaN   NaN      3.0   NaN
3038849     11        2011        jena    12.0       3.0   9.0      6.0   NaN
3038850     11        2011       lenka     3.0       NaN   NaN      3.0   NaN
3038851     11        2011     mahanta     NaN       3.0   NaN      3.0   NaN
3038852     11        2011       majhi     3.0       NaN   NaN      NaN   3.0
3038853     11        2011   mohapatra     3.0       NaN   NaN      3.0   NaN
3038854     11        2011       munda     3.0       NaN   NaN      NaN   3.0
3038855     11        2011         nag     3.0       NaN   NaN      NaN   3.0
3038856     11        2011        naik     3.0       NaN   NaN      NaN   3.0
3038857     11        2011      parida     3.0       NaN   NaN      3.0   NaN
3038858     11        2011     pradhan     3.0       9.0   NaN      NaN  12.0
3038859     11        2011        rout     6.0       NaN   NaN      6.0   NaN
3038860     11        2011       sahoo     3.0       NaN   NaN      3.0   NaN
3038861     11        2011       samal     NaN       3.0   NaN      3.0   NaN
3038862     11        2011     sarakar     NaN       3.0   NaN      3.0   NaN

[3038863 rows x 8 columns]

In [11]:
gdf.fillna(0, inplace=True)
gdf.astype({'n_male': int, 'n_female': int, 'n_sc': int, 'n_st': int, 'n_other': int})

/opt/venv3/lib/python3.5/site-packages/pandas/core/frame.py:4034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

         state  birth_year   last_name  n_male  n_female  n_sc  n_other  n_st
0            0        1881      chakma       6         0     0        6     0
1            0        1881         eke       6         0     0        0     6
2            0        1883         dui       0         6     0        0     6
3            0        1883         ete       6         0     0        0     6
4            0        1883        kawa       6         0     0        0     6
5            0        1884       dagam       6         0     0        0     6
6            0        1884        riba       6         0     0        0     6
7            0        1885      tabang       6         0     0        0     6
8            0        1887        raje       6         0     0        0     6
9            0        1888         ali       6         0     0        0     6
10           0        1888     mossang       6         0     0        0     6
11           0        1889     singpho       6         0     0        0     6
12           0        1891     chandra       6         0     0        6     0
13           0        1891     chotton       0         6     0        0     6
14           0        1894      chakma       6         0     0        6     0
15           0        1895  bosumotari       0         6     0        6     0
16           0        1895        diru       6         0     0        0     6
17           0        1896      namati       6         0     0        0     6
18           0        1899        duri       6         0     0        0     6
19           0        1901      chader       0         6     0        0     6
20           0        1901      tamang       6         0     0        6     0
21           0        1901        topu       6         0     0        0     6
22           0        1903      chakma       6         0     0        6     0
23           0        1903       jamoh       6         0     0        0     6
24           0        1903       tapok       0         6     0        0     6
25           0        1903       tatin       6         0     0        0     6
26           0        1904      bellai       6         0     0        0     6
27           0        1904         ete       6         0     0        0     6
28           0        1904       taggu       6         0     0        0     6
29           0        1904        take       6         0     0        0     6
...        ...         ...         ...     ...       ...   ...      ...   ...
3038833     11        2010     pradhan       0         6     3        0     3
3038834     11        2010      prusty       0         3     0        3     0
3038835     11        2010      ranjan       3         0     0        3     0
3038836     11        2010         ray       3         0     0        0     3
3038837     11        2010        rout       6         3     0        9     0
3038838     11        2010       sabar       3         0     0        0     3
3038839     11        2010       sahoo       3         0     3        0     0
3038840     11        2010        sahu       3         3     0        6     0
3038841     11        2010         son       3         0     0        0     3
3038842     11        2010       swani       0         3     0        3     0
3038843     11        2010     tarenia       3         0     0        3     0
3038844     11        2011      behera       3         0     0        3     0
3038845     11        2011         das       3         0     0        3     0
3038846     11        2011       digal       0         3     3        0     0
3038847     11        2011     gagarai       3         0     0        0     3
3038848     11        2011        giri       3         0     0        3     0
3038849     11        2011        jena      12         3     9        6     0
3038850     11        2011       lenka       3         0     0        3     0
3038851     11        2011     mahanta       0         3     0        3     0
3038852     11        2011       majhi       3         0     0        0     3
3038853     11        2011   mohapatra       3         0     0        3     0
3038854     11        2011       munda       3         0     0        0     3
3038855     11        2011         nag       3         0     0        0     3
3038856     11        2011        naik       3         0     0        0     3
3038857     11        2011      parida       3         0     0        3     0
3038858     11        2011     pradhan       3         9     0        0    12
3038859     11        2011        rout       6         0     0        6     0
3038860     11        2011       sahoo       3         0     0        3     0
3038861     11        2011       samal       0         3     0        3     0
3038862     11        2011     sarakar       0         3     0        3     0

[3038863 rows x 8 columns]

In [12]:
gdf.to_csv('/opt/data/secc/secc_state0_9_year_ln_outkast.csv.gz', index=False, compression='gzip')

In [13]:
bdf = gdf.groupby(['last_name']).agg({'n_sc': 'sum', 'n_other': 'sum', 'n_st': 'sum', 'n_male': 'sum', 'n_female': 'sum'}).reset_index()
bdf

       last_name  n_female    n_st   n_sc  n_male  n_other
0           aaba      57.0     3.0   96.0   636.0    594.0
1        aabadar       6.0     0.0    0.0   135.0    141.0
2         aabaji      21.0    21.0   60.0   492.0    432.0
3         aabale       9.0     0.0    3.0   168.0    174.0
4        aabarao       6.0     0.0    9.0   147.0    144.0
5          aabas       6.0     0.0    3.0    99.0    102.0
6      aabasaheb      21.0     3.0    3.0   246.0    261.0
7         aabdin      15.0     0.0    0.0   168.0    183.0
8        aabhale      36.0     0.0    0.0    81.0    117.0
9        aabhare      18.0     0.0    3.0   195.0    210.0
10         aabid      12.0     0.0    3.0  1044.0   1053.0
11       aabnave      27.0     0.0   99.0   102.0     30.0
12          aabu       9.0     0.0    0.0   105.0    114.0
13         aabuj      57.0     0.0    0.0   477.0    534.0
14        aachar       3.0     0.0   51.0   123.0     75.0
15       aachare      24.0     0.0   21.0    99.0    102.0
16       aachari      30.0   207.0    0.0   309.0    132.0
17       aachary      24.0    18.0   66.0   435.0    375.0
18      aacharya      66.0    27.0  108.0   717.0    648.0
19        aachre       9.0     0.0    0.0   186.0    195.0
20           aad      12.0   222.0    6.0   234.0     18.0
21        aadaga      27.0   228.0    0.0   201.0      0.0
22      aadagale      51.0     0.0  306.0   315.0     60.0
23         aadak      21.0     0.0    0.0   291.0    312.0
24        aadake     108.0     6.0   15.0   579.0    666.0
25     aadalinge       9.0     0.0    0.0   171.0    180.0
26         aadam      90.0     6.0   15.0   639.0    708.0
27      aadamane      27.0     0.0   57.0   177.0    147.0
28     aadambhai      30.0     3.0    0.0   210.0    237.0
29       aadasul      42.0     3.0   54.0   477.0    462.0
...          ...       ...     ...    ...     ...      ...
55227     zoting      72.0     0.0   81.0   573.0    564.0
55228      zoura     123.0     0.0    0.0     3.0    126.0
55229     zubair      12.0     3.0    3.0   615.0    621.0
55230      zuber       0.0     0.0    0.0   358.0    358.0
55231      zugar      21.0     3.0    0.0   111.0    129.0
55232     zugare     165.0  1533.0    6.0  1419.0     45.0
55233       zuge      12.0     0.0    0.0   177.0    189.0
55234      zugre      18.0   231.0    0.0   219.0      6.0
55235      zuhra      99.0     0.0    0.0    15.0    114.0
55236      zujam      60.0     0.0    0.0   285.0    345.0
55237   zulasana       3.0     0.0    0.0   132.0    135.0
55238    zulasna       6.0     0.0    0.0   126.0    132.0
55239     zumbar      21.0     6.0   63.0   247.0    199.0
55240     zumman       3.0     0.0    6.0   111.0    108.0
55241     zunaid       0.0     0.0    0.0   144.0    144.0
55242    zungare      30.0    33.0   21.0   249.0    225.0
55243      zunge       6.0     0.0    0.0    99.0    105.0
55244     zunjar      18.0    54.0    3.0   171.0    132.0
55245    zunjare      99.0    57.0  636.0   885.0    291.0
55246      zunje       6.0     0.0    0.0   147.0    153.0
55247      zunza      45.0   111.0    0.0   324.0    258.0
55248    zunzare      15.0     3.0  108.0   138.0     42.0
55249     zurade      30.0   213.0    0.0   201.0     18.0
55250     zurale      48.0     3.0    0.0   276.0    321.0
55251    zurange      18.0     0.0    0.0   198.0    216.0
55252      zurde      15.0   132.0    0.0   117.0      0.0
55253       zure      93.0    75.0    0.0   432.0    450.0
55254    zurunge       9.0     0.0    0.0   183.0    192.0
55255       zute      21.0    15.0   18.0   303.0    291.0
55256      zyate      30.0   294.0    0.0   288.0     24.0

[55257 rows x 6 columns]