In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/opt/data/secc/secc_state_name_age_sex_social_cat_state10_18.csv.gz')
df

           state gender social_cat  birth_year  last_name
0             10      m          t        1962        NaN
1             10      m          t        1955        NaN
2             10      m          t        1972        NaN
3             10      m          t        1967        ths
4             10      m          t        1957        NaN
5             10      m          t        1985        NaN
6             10      m          t        1979        NaN
7             10      m          t        1981        NaN
8             10      m          t        1985        NaN
9             10      m          t        1985        NaN
10            10      f          t        1989        NaN
11            10      m          t        1984        NaN
12            10      m          t        1994        NaN
13            10      m          t        1989        NaN
14            10      m          t        1981        NaN
15            10      m          t        1962        NaN
16            10      m          t        1955        NaN
17            10      m          t        1972        NaN
18            10      m          t        1967        ths
19            10      m          t        1957        NaN
20            10      m          t        1985        NaN
21            10      m          t        1979        NaN
22            10      m          t        1981        NaN
23            10      m          t        1985        NaN
24            10      m          t        1985        NaN
25            10      f          t        1989        NaN
26            10      m          t        1984        NaN
27            10      m          t        1994        NaN
28            10      m          t        1989        NaN
29            10      m          t        1981        NaN
...          ...    ...        ...         ...        ...
222504494     18      m          c        1970     mandal
222504495     18      m          c        1937      maity
222504496     18      m          c        1979     mandal
222504497     18      f          c        1976     mandal
222504498     18      m          c        1969      maity
222504499     18      m          c        1962     mandal
222504500     18      m          c        1959      maity
222504501     18      m          c        1961      maity
222504502     18      m          c        1911      maity
222504503     18      m          c        1971      maity
222504504     18      m          c        1964      maity
222504505     18      m          c        1969      maity
222504506     18      m          c        1977      maity
222504507     18      m          c        1956      maity
222504508     18      m          c        1972     mandal
222504509     18      m          c        1966      maity
222504510     18      m          o        1977  mahapatra
222504511     18      m          c        1974      maity
222504512     18      m          c        1969     mandal
222504513     18      m          c        1944      maity
222504514     18      m          c        1946      hajra
222504515     18      m          c        1987      maity
222504516     18      m          c        1967      maity
222504517     18      m          c        1955      maity
222504518     18      m          c        1971      maity
222504519     18      m          c        1976      maity
222504520     18      m          c        1974      maity
222504521     18      m          c        1969      maity
222504522     18      m          o        1949  mahapatra
222504523     18      m          o        1944        das

[222504524 rows x 5 columns]

In [3]:
df.dropna(subset=['last_name'], inplace=True)
df.drop(df[~df.last_name.str.contains('^[a-z]{2,}')].index, inplace=True)
df.drop(df[df.last_name.str.contains('\.')].index, inplace=True)
df

           state gender social_cat  birth_year  last_name
3             10      m          t        1967        ths
18            10      m          t        1967        ths
33            10      m          t        1967        ths
45            10      m          t        1980      awomi
46            10      m          t        1976     achumi
47            10      m          t        1967     achumi
48            10      m          t        1966       kiba
49            10      m          t        1955     yeptho
50            10      f          t        1954      shohe
52            10      f          t        1971      shohe
53            10      m          t        1934      acumi
54            10      m          t        1984      awomi
55            10      m          t        1949      ayemi
56            10      m          t        1934      ayemi
57            10      m          t        1977      shohe
58            10      m          t        1967      shone
59            10      f          t        1956      shohe
60            10      m          t        1963      awomi
61            10      m          t        1940      shohe
62            10      m          t        1957      shohe
63            10      m          t        1973     achumi
64            10      m          t        1960      zhimo
65            10      m          t        1983     achumi
66            10      m          t        1944     achumi
67            10      m          t        1969     achumi
68            10      m          t        1964     achumi
69            10      m          t        1973    bahadur
70            10      m          o        1974      thapa
71            10      m          o        1968     pangmi
72            10      m          o        1972   gormokar
...          ...    ...        ...         ...        ...
222504494     18      m          c        1970     mandal
222504495     18      m          c        1937      maity
222504496     18      m          c        1979     mandal
222504497     18      f          c        1976     mandal
222504498     18      m          c        1969      maity
222504499     18      m          c        1962     mandal
222504500     18      m          c        1959      maity
222504501     18      m          c        1961      maity
222504502     18      m          c        1911      maity
222504503     18      m          c        1971      maity
222504504     18      m          c        1964      maity
222504505     18      m          c        1969      maity
222504506     18      m          c        1977      maity
222504507     18      m          c        1956      maity
222504508     18      m          c        1972     mandal
222504509     18      m          c        1966      maity
222504510     18      m          o        1977  mahapatra
222504511     18      m          c        1974      maity
222504512     18      m          c        1969     mandal
222504513     18      m          c        1944      maity
222504514     18      m          c        1946      hajra
222504515     18      m          c        1987      maity
222504516     18      m          c        1967      maity
222504517     18      m          c        1955      maity
222504518     18      m          c        1971      maity
222504519     18      m          c        1976      maity
222504520     18      m          c        1974      maity
222504521     18      m          c        1969      maity
222504522     18      m          o        1949  mahapatra
222504523     18      m          o        1944        das

[164067729 rows x 5 columns]

* i think it makes sense to only release data where count for last_name/first_name is > 100
* it will take out a bunch of weird names for now

In [4]:
adf = df[df['last_name'].groupby(df['last_name']).transform('size')>100]
adf

           state gender social_cat  birth_year  last_name
45            10      m          t        1980      awomi
46            10      m          t        1976     achumi
47            10      m          t        1967     achumi
48            10      m          t        1966       kiba
49            10      m          t        1955     yeptho
50            10      f          t        1954      shohe
52            10      f          t        1971      shohe
54            10      m          t        1984      awomi
55            10      m          t        1949      ayemi
56            10      m          t        1934      ayemi
57            10      m          t        1977      shohe
59            10      f          t        1956      shohe
60            10      m          t        1963      awomi
61            10      m          t        1940      shohe
62            10      m          t        1957      shohe
63            10      m          t        1973     achumi
64            10      m          t        1960      zhimo
65            10      m          t        1983     achumi
66            10      m          t        1944     achumi
67            10      m          t        1969     achumi
68            10      m          t        1964     achumi
69            10      m          t        1973    bahadur
70            10      m          o        1974      thapa
73            10      m          t        1974      shohe
75            10      m          t        1954     chishi
76            10      f          t        1964       kiba
77            10      m          t        1964      ayemi
78            10      f          t        1947       kiba
79            10      m          t        1971     achumi
80            10      m          t        1980     achumi
...          ...    ...        ...         ...        ...
222504494     18      m          c        1970     mandal
222504495     18      m          c        1937      maity
222504496     18      m          c        1979     mandal
222504497     18      f          c        1976     mandal
222504498     18      m          c        1969      maity
222504499     18      m          c        1962     mandal
222504500     18      m          c        1959      maity
222504501     18      m          c        1961      maity
222504502     18      m          c        1911      maity
222504503     18      m          c        1971      maity
222504504     18      m          c        1964      maity
222504505     18      m          c        1969      maity
222504506     18      m          c        1977      maity
222504507     18      m          c        1956      maity
222504508     18      m          c        1972     mandal
222504509     18      m          c        1966      maity
222504510     18      m          o        1977  mahapatra
222504511     18      m          c        1974      maity
222504512     18      m          c        1969     mandal
222504513     18      m          c        1944      maity
222504514     18      m          c        1946      hajra
222504515     18      m          c        1987      maity
222504516     18      m          c        1967      maity
222504517     18      m          c        1955      maity
222504518     18      m          c        1971      maity
222504519     18      m          c        1976      maity
222504520     18      m          c        1974      maity
222504521     18      m          c        1969      maity
222504522     18      m          o        1949  mahapatra
222504523     18      m          o        1944        das

[157667250 rows x 5 columns]

In [5]:
adf['last_name'].groupby(adf['last_name']).size()

last_name
aabad            348
aabdeen          189
aabdin           195
aabid            558
aachari          588
aachary          609
aacharya         519
aada             108
aadhar          1272
aadhi            114
aadhimoolam      432
aadhimulam       207
aadil            201
aadivasi         357
aadok            132
aahamad          198
aahari           249
aahir            273
aahmad           369
aajad            393
aajam            612
aakil            483
aalam          11637
aalan            267
aali            1713
aalim            423
aalm             525
aalvar           135
aameen           132
aameta           543
               ...
zaleel           177
zalil            732
zama             264
zamadar          510
zamal           1299
zamaluddin       480
zaman            978
zameel           333
zamil            543
zamir            237
zamiruddin       159
zamirul          108
zan              336
zao              108
zasimuddin       144
zaved            216
zeliang          129
zhimo           2562
zhimomi          870
zholia           249
zhotso           255
zikriya          234
zilani           123
ziyarul          162
zoha             120
zubair           135
zuber            117
zulfikar         102
zumu             129
zutso            129
Name: last_name, Length: 32223, dtype: int64

In [6]:
gdf = adf.groupby(['state', 'birth_year', 'last_name']).agg({'gender': 'value_counts', 'social_cat': 'value_counts'}).unstack()

In [7]:
gdf

                   gender                     social_cat
                        c     f     m   o   t          c   f   m     o     t
10 1882 longkumer     NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1894 kinny         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1899 konyak        NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        sumi          NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1900 sangtam       NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1901 sumi          NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1902 sumi          NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        wati          NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1903 awomi         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        kath          NaN   3.0   NaN NaN NaN        NaN NaN NaN   NaN   3.0
        kithan        NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        sangtam       NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        sumi          NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1904 kikon         NaN   3.0   NaN NaN NaN        NaN NaN NaN   NaN   3.0
        phom          NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        singh         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   3.0   NaN
        yeptho        NaN   3.0   NaN NaN NaN        NaN NaN NaN   NaN   3.0
        zhimo         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1905 kir           NaN   3.0   NaN NaN NaN        NaN NaN NaN   NaN   3.0
        sangtam       NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        sumi          NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1906 kupa          NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        lotha         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1907 kikhi         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        odyuo         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        pienyu        NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1908 yimchunger    NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
   1909 assumi        NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        aye           NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
        ayemi         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   NaN   3.0
...                   ...   ...   ...  ..  ..        ...  ..  ..   ...   ...
18 2011 rajak         NaN   NaN   6.0 NaN NaN        NaN NaN NaN   6.0   NaN
        roy           NaN   NaN  18.0 NaN NaN        6.0 NaN NaN  12.0   NaN
        sahu          NaN   NaN   3.0 NaN NaN        NaN NaN NaN   3.0   NaN
        sajal         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   3.0   NaN
        sam           NaN   NaN   3.0 NaN NaN        NaN NaN NaN   3.0   NaN
        samant        NaN   NaN   3.0 NaN NaN        NaN NaN NaN   3.0   NaN
        samanta       NaN   NaN   3.0 NaN NaN        NaN NaN NaN   3.0   NaN
        sana          NaN   NaN   6.0 NaN NaN        NaN NaN NaN   6.0   NaN
        santar        NaN   NaN   6.0 NaN NaN        NaN NaN NaN   6.0   NaN
        santra        NaN   NaN   6.0 NaN NaN        6.0 NaN NaN   NaN   NaN
        sardar        NaN   6.0   6.0 NaN NaN        NaN NaN NaN   6.0   6.0
        saren         NaN   NaN   6.0 NaN NaN        NaN NaN NaN   NaN   6.0
        sarkar        NaN   3.0  15.0 NaN NaN       15.0 NaN NaN   3.0   NaN
        sau           NaN   3.0   NaN NaN NaN        NaN NaN NaN   3.0   NaN
        sekh          NaN   NaN   3.0 NaN NaN        NaN NaN NaN   3.0   NaN
        shau          NaN   NaN   3.0 NaN NaN        3.0 NaN NaN   NaN   NaN
        shekh         NaN   NaN   6.0 NaN NaN        NaN NaN NaN   6.0   NaN
        siddika       NaN   6.0   NaN NaN NaN        NaN NaN NaN   6.0   NaN
        sing          NaN  12.0   NaN NaN NaN        NaN NaN NaN   NaN  12.0
        singh         NaN   NaN   6.0 NaN NaN        NaN NaN NaN   6.0   NaN
        sorkar        NaN   NaN   6.0 NaN NaN        NaN NaN NaN   6.0   NaN
        sufian        NaN   NaN   6.0 NaN NaN        NaN NaN NaN   6.0   NaN
        sultana       NaN   6.0   NaN NaN NaN        NaN NaN NaN   6.0   NaN
        surin         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   3.0   NaN
        tanti         NaN   6.0   NaN NaN NaN        NaN NaN NaN   6.0   NaN
        tarafdar      NaN   NaN   6.0 NaN NaN        6.0 NaN NaN   NaN   NaN
        thakuri       NaN   NaN   3.0 NaN NaN        NaN NaN NaN   3.0   NaN
        topno         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   3.0   NaN
        tudu          NaN   3.0   NaN NaN NaN        NaN NaN NaN   NaN   3.0
        xalxo         NaN   NaN   3.0 NaN NaN        NaN NaN NaN   3.0   NaN

[1725862 rows x 10 columns]

In [8]:
gdf.reset_index(inplace=True)
gdf

        level_0 level_1     level_2 gender                     social_cat      \
                                         c     f     m   o   t          c   f
0            10    1882   longkumer    NaN   NaN   3.0 NaN NaN        NaN NaN
1            10    1894       kinny    NaN   NaN   3.0 NaN NaN        NaN NaN
2            10    1899      konyak    NaN   NaN   3.0 NaN NaN        NaN NaN
3            10    1899        sumi    NaN   NaN   3.0 NaN NaN        NaN NaN
4            10    1900     sangtam    NaN   NaN   3.0 NaN NaN        NaN NaN
5            10    1901        sumi    NaN   NaN   3.0 NaN NaN        NaN NaN
6            10    1902        sumi    NaN   NaN   3.0 NaN NaN        NaN NaN
7            10    1902        wati    NaN   NaN   3.0 NaN NaN        NaN NaN
8            10    1903       awomi    NaN   NaN   3.0 NaN NaN        NaN NaN
9            10    1903        kath    NaN   3.0   NaN NaN NaN        NaN NaN
10           10    1903      kithan    NaN   NaN   3.0 NaN NaN        NaN NaN
11           10    1903     sangtam    NaN   NaN   3.0 NaN NaN        NaN NaN
12           10    1903        sumi    NaN   NaN   3.0 NaN NaN        NaN NaN
13           10    1904       kikon    NaN   3.0   NaN NaN NaN        NaN NaN
14           10    1904        phom    NaN   NaN   3.0 NaN NaN        NaN NaN
15           10    1904       singh    NaN   NaN   3.0 NaN NaN        NaN NaN
16           10    1904      yeptho    NaN   3.0   NaN NaN NaN        NaN NaN
17           10    1904       zhimo    NaN   NaN   3.0 NaN NaN        NaN NaN
18           10    1905         kir    NaN   3.0   NaN NaN NaN        NaN NaN
19           10    1905     sangtam    NaN   NaN   3.0 NaN NaN        NaN NaN
20           10    1905        sumi    NaN   NaN   3.0 NaN NaN        NaN NaN
21           10    1906        kupa    NaN   NaN   3.0 NaN NaN        NaN NaN
22           10    1906       lotha    NaN   NaN   3.0 NaN NaN        NaN NaN
23           10    1907       kikhi    NaN   NaN   3.0 NaN NaN        NaN NaN
24           10    1907       odyuo    NaN   NaN   3.0 NaN NaN        NaN NaN
25           10    1907      pienyu    NaN   NaN   3.0 NaN NaN        NaN NaN
26           10    1908  yimchunger    NaN   NaN   3.0 NaN NaN        NaN NaN
27           10    1909      assumi    NaN   NaN   3.0 NaN NaN        NaN NaN
28           10    1909         aye    NaN   NaN   3.0 NaN NaN        NaN NaN
29           10    1909       ayemi    NaN   NaN   3.0 NaN NaN        NaN NaN
...         ...     ...         ...    ...   ...   ...  ..  ..        ...  ..
1725832      18    2011       rajak    NaN   NaN   6.0 NaN NaN        NaN NaN
1725833      18    2011         roy    NaN   NaN  18.0 NaN NaN        6.0 NaN
1725834      18    2011        sahu    NaN   NaN   3.0 NaN NaN        NaN NaN
1725835      18    2011       sajal    NaN   NaN   3.0 NaN NaN        NaN NaN
1725836      18    2011         sam    NaN   NaN   3.0 NaN NaN        NaN NaN
1725837      18    2011      samant    NaN   NaN   3.0 NaN NaN        NaN NaN
1725838      18    2011     samanta    NaN   NaN   3.0 NaN NaN        NaN NaN
1725839      18    2011        sana    NaN   NaN   6.0 NaN NaN        NaN NaN
1725840      18    2011      santar    NaN   NaN   6.0 NaN NaN        NaN NaN
1725841      18    2011      santra    NaN   NaN   6.0 NaN NaN        6.0 NaN
1725842      18    2011      sardar    NaN   6.0   6.0 NaN NaN        NaN NaN
1725843      18    2011       saren    NaN   NaN   6.0 NaN NaN        NaN NaN
1725844      18    2011      sarkar    NaN   3.0  15.0 NaN NaN       15.0 NaN
1725845      18    2011         sau    NaN   3.0   NaN NaN NaN        NaN NaN
1725846      18    2011        sekh    NaN   NaN   3.0 NaN NaN        NaN NaN
1725847      18    2011        shau    NaN   NaN   3.0 NaN NaN        3.0 NaN
1725848      18    2011       shekh    NaN   NaN   6.0 NaN NaN        NaN NaN
1725849      18    2011     siddika    NaN   6.0   NaN NaN NaN        NaN NaN
1725850      18    2011        sing    NaN  12.0   NaN NaN NaN        NaN NaN
1725851      18    2011       singh    NaN   NaN   6.0 NaN NaN        NaN NaN
1725852      18    2011      sorkar    NaN   NaN   6.0 NaN NaN        NaN NaN
1725853      18    2011      sufian    NaN   NaN   6.0 NaN NaN        NaN NaN
1725854      18    2011     sultana    NaN   6.0   NaN NaN NaN        NaN NaN
1725855      18    2011       surin    NaN   NaN   3.0 NaN NaN        NaN NaN
1725856      18    2011       tanti    NaN   6.0   NaN NaN NaN        NaN NaN
1725857      18    2011    tarafdar    NaN   NaN   6.0 NaN NaN        6.0 NaN
1725858      18    2011     thakuri    NaN   NaN   3.0 NaN NaN        NaN NaN
1725859      18    2011       topno    NaN   NaN   3.0 NaN NaN        NaN NaN
1725860      18    2011        tudu    NaN   3.0   NaN NaN NaN        NaN NaN
1725861      18    2011       xalxo    NaN   NaN   3.0 NaN NaN        NaN NaN


          m     o     t
0       NaN   NaN   3.0
1       NaN   NaN   3.0
2       NaN   NaN   3.0
3       NaN   NaN   3.0
4       NaN   NaN   3.0
5       NaN   NaN   3.0
6       NaN   NaN   3.0
7       NaN   NaN   3.0
8       NaN   NaN   3.0
9       NaN   NaN   3.0
10      NaN   NaN   3.0
11      NaN   NaN   3.0
12      NaN   NaN   3.0
13      NaN   NaN   3.0
14      NaN   NaN   3.0
15      NaN   3.0   NaN
16      NaN   NaN   3.0
17      NaN   NaN   3.0
18      NaN   NaN   3.0
19      NaN   NaN   3.0
20      NaN   NaN   3.0
21      NaN   NaN   3.0
22      NaN   NaN   3.0
23      NaN   NaN   3.0
24      NaN   NaN   3.0
25      NaN   NaN   3.0
26      NaN   NaN   3.0
27      NaN   NaN   3.0
28      NaN   NaN   3.0
29      NaN   NaN   3.0
...      ..   ...   ...
1725832 NaN   6.0   NaN
1725833 NaN  12.0   NaN
1725834 NaN   3.0   NaN
1725835 NaN   3.0   NaN
1725836 NaN   3.0   NaN
1725837 NaN   3.0   NaN
1725838 NaN   3.0   NaN
1725839 NaN   6.0   NaN
1725840 NaN   6.0   NaN
1725841 NaN   NaN   NaN
1725842 NaN   6.0   6.0
1725843 NaN   NaN   6.0
1725844 NaN   3.0   NaN
1725845 NaN   3.0   NaN
1725846 NaN   3.0   NaN
1725847 NaN   NaN   NaN
1725848 NaN   6.0   NaN
1725849 NaN   6.0   NaN
1725850 NaN   NaN  12.0
1725851 NaN   6.0   NaN
1725852 NaN   6.0   NaN
1725853 NaN   6.0   NaN
1725854 NaN   6.0   NaN
1725855 NaN   3.0   NaN
1725856 NaN   6.0   NaN
1725857 NaN   NaN   NaN
1725858 NaN   3.0   NaN
1725859 NaN   3.0   NaN
1725860 NaN   NaN   3.0
1725861 NaN   3.0   NaN

[1725862 rows x 13 columns]

In [9]:
gdf.columns = ['_'.join(col).strip() for col in gdf.columns.values]
gdf

,level_0_,level_1_,level_2_,gender_c,gender_f,gender_m,gender_o,gender_t,social_cat_c,social_cat_f,social_cat_m,social_cat_o,social_cat_t
0,10,1882,longkumer,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1,10,1894,kinny,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
2,10,1899,konyak,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
3,10,1899,sumi,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
4,10,1900,sangtam,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
5,10,1901,sumi,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
6,10,1902,sumi,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
7,10,1902,wati,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
8,10,1903,awomi,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
9,10,1903,kath,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
10,10,1903,kithan,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
11,10,1903,sangtam,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
12,10,1903,sumi,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
13,10,1904,kikon,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
14,10,1904,phom,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
15,10,1904,singh,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
16,10,1904,yeptho,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
17,10,1904,zhimo,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
18,10,1905,kir,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
19,10,1905,sangtam,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
20,10,1905,sumi,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
21,10,1906,kupa,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
22,10,1906,lotha,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
23,10,1907,kikhi,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
24,10,1907,odyuo,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
25,10,1907,pienyu,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
26,10,1908,yimchunger,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
27,10,1909,assumi,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
28,10,1909,aye,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
29,10,1909,ayemi,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1725832,18,2011,rajak,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
1725833,18,2011,roy,NaN,NaN,18.0,NaN,NaN,6.0,NaN,NaN,12.0,NaN
1725834,18,2011,sahu,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
1725835,18,2011,sajal,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
1725836,18,2011,sam,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
1725837,18,2011,samant,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
1725838,18,2011,samanta,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
1725839,18,2011,sana,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
1725840,18,2011,santar,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
1725841,18,2011,santra,NaN,NaN,6.0,NaN,NaN,6.0,NaN,NaN,NaN,NaN
1725842,18,2011,sardar,NaN,6.0,6.0,NaN,NaN,NaN,NaN,NaN,6.0,6.0
1725843,18,2011,saren,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
1725844,18,2011,sarkar,NaN,3.0,15.0,NaN,NaN,15.0,NaN,NaN,3.0,NaN
1725845,18,2011,sau,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
1725846,18,2011,sekh,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
1725847,18,2011,shau,NaN,NaN,3.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN
1725848,18,2011,shekh,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
1725849,18,2011,siddika,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN
1725850,18,2011,sing,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
1725851,18,2011,singh,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
1725852,18,2011,sorkar,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
1725853,18,2011,sufian,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN
1725854,18,2011,sultana,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN
1725855,18,2011,surin,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
1725856,18,2011,tanti,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN
1725857,18,2011,tarafdar,NaN,NaN,6.0,NaN,NaN,6.0,NaN,NaN,NaN,NaN
1725858,18,2011,thakuri,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
1725859,18,2011,topno,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN
1725860,18,2011,tudu,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
1725861,18,2011,xalxo,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN

In [10]:
gdf = gdf[['level_0_', 'level_1_', 'level_2_', 'gender_m', 'gender_f', 'social_cat_c', 'social_cat_o', 'social_cat_t']]
gdf.columns = ['state', 'birth_year', 'last_name', 'n_male', 'n_female', 'n_sc', 'n_other', 'n_st']
gdf

         state  birth_year   last_name  n_male  n_female  n_sc  n_other  n_st
0           10        1882   longkumer     3.0       NaN   NaN      NaN   3.0
1           10        1894       kinny     3.0       NaN   NaN      NaN   3.0
2           10        1899      konyak     3.0       NaN   NaN      NaN   3.0
3           10        1899        sumi     3.0       NaN   NaN      NaN   3.0
4           10        1900     sangtam     3.0       NaN   NaN      NaN   3.0
5           10        1901        sumi     3.0       NaN   NaN      NaN   3.0
6           10        1902        sumi     3.0       NaN   NaN      NaN   3.0
7           10        1902        wati     3.0       NaN   NaN      NaN   3.0
8           10        1903       awomi     3.0       NaN   NaN      NaN   3.0
9           10        1903        kath     NaN       3.0   NaN      NaN   3.0
10          10        1903      kithan     3.0       NaN   NaN      NaN   3.0
11          10        1903     sangtam     3.0       NaN   NaN      NaN   3.0
12          10        1903        sumi     3.0       NaN   NaN      NaN   3.0
13          10        1904       kikon     NaN       3.0   NaN      NaN   3.0
14          10        1904        phom     3.0       NaN   NaN      NaN   3.0
15          10        1904       singh     3.0       NaN   NaN      3.0   NaN
16          10        1904      yeptho     NaN       3.0   NaN      NaN   3.0
17          10        1904       zhimo     3.0       NaN   NaN      NaN   3.0
18          10        1905         kir     NaN       3.0   NaN      NaN   3.0
19          10        1905     sangtam     3.0       NaN   NaN      NaN   3.0
20          10        1905        sumi     3.0       NaN   NaN      NaN   3.0
21          10        1906        kupa     3.0       NaN   NaN      NaN   3.0
22          10        1906       lotha     3.0       NaN   NaN      NaN   3.0
23          10        1907       kikhi     3.0       NaN   NaN      NaN   3.0
24          10        1907       odyuo     3.0       NaN   NaN      NaN   3.0
25          10        1907      pienyu     3.0       NaN   NaN      NaN   3.0
26          10        1908  yimchunger     3.0       NaN   NaN      NaN   3.0
27          10        1909      assumi     3.0       NaN   NaN      NaN   3.0
28          10        1909         aye     3.0       NaN   NaN      NaN   3.0
29          10        1909       ayemi     3.0       NaN   NaN      NaN   3.0
...        ...         ...         ...     ...       ...   ...      ...   ...
1725832     18        2011       rajak     6.0       NaN   NaN      6.0   NaN
1725833     18        2011         roy    18.0       NaN   6.0     12.0   NaN
1725834     18        2011        sahu     3.0       NaN   NaN      3.0   NaN
1725835     18        2011       sajal     3.0       NaN   NaN      3.0   NaN
1725836     18        2011         sam     3.0       NaN   NaN      3.0   NaN
1725837     18        2011      samant     3.0       NaN   NaN      3.0   NaN
1725838     18        2011     samanta     3.0       NaN   NaN      3.0   NaN
1725839     18        2011        sana     6.0       NaN   NaN      6.0   NaN
1725840     18        2011      santar     6.0       NaN   NaN      6.0   NaN
1725841     18        2011      santra     6.0       NaN   6.0      NaN   NaN
1725842     18        2011      sardar     6.0       6.0   NaN      6.0   6.0
1725843     18        2011       saren     6.0       NaN   NaN      NaN   6.0
1725844     18        2011      sarkar    15.0       3.0  15.0      3.0   NaN
1725845     18        2011         sau     NaN       3.0   NaN      3.0   NaN
1725846     18        2011        sekh     3.0       NaN   NaN      3.0   NaN
1725847     18        2011        shau     3.0       NaN   3.0      NaN   NaN
1725848     18        2011       shekh     6.0       NaN   NaN      6.0   NaN
1725849     18        2011     siddika     NaN       6.0   NaN      6.0   NaN
1725850     18        2011        sing     NaN      12.0   NaN      NaN  12.0
1725851     18        2011       singh     6.0       NaN   NaN      6.0   NaN
1725852     18        2011      sorkar     6.0       NaN   NaN      6.0   NaN
1725853     18        2011      sufian     6.0       NaN   NaN      6.0   NaN
1725854     18        2011     sultana     NaN       6.0   NaN      6.0   NaN
1725855     18        2011       surin     3.0       NaN   NaN      3.0   NaN
1725856     18        2011       tanti     NaN       6.0   NaN      6.0   NaN
1725857     18        2011    tarafdar     6.0       NaN   6.0      NaN   NaN
1725858     18        2011     thakuri     3.0       NaN   NaN      3.0   NaN
1725859     18        2011       topno     3.0       NaN   NaN      3.0   NaN
1725860     18        2011        tudu     NaN       3.0   NaN      NaN   3.0
1725861     18        2011       xalxo     3.0       NaN   NaN      3.0   NaN

[1725862 rows x 8 columns]

In [16]:
gdf.fillna(0, inplace=True)
gdf.astype({'n_male': int, 'n_female': int, 'n_sc': int, 'n_st': int, 'n_other': int})

/opt/venv3/lib/python3.5/site-packages/pandas/core/frame.py:4034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

         state  birth_year   last_name  n_male  n_female  n_sc  n_other  n_st
0           10        1882   longkumer       3         0     0        0     3
1           10        1894       kinny       3         0     0        0     3
2           10        1899      konyak       3         0     0        0     3
3           10        1899        sumi       3         0     0        0     3
4           10        1900     sangtam       3         0     0        0     3
5           10        1901        sumi       3         0     0        0     3
6           10        1902        sumi       3         0     0        0     3
7           10        1902        wati       3         0     0        0     3
8           10        1903       awomi       3         0     0        0     3
9           10        1903        kath       0         3     0        0     3
10          10        1903      kithan       3         0     0        0     3
11          10        1903     sangtam       3         0     0        0     3
12          10        1903        sumi       3         0     0        0     3
13          10        1904       kikon       0         3     0        0     3
14          10        1904        phom       3         0     0        0     3
15          10        1904       singh       3         0     0        3     0
16          10        1904      yeptho       0         3     0        0     3
17          10        1904       zhimo       3         0     0        0     3
18          10        1905         kir       0         3     0        0     3
19          10        1905     sangtam       3         0     0        0     3
20          10        1905        sumi       3         0     0        0     3
21          10        1906        kupa       3         0     0        0     3
22          10        1906       lotha       3         0     0        0     3
23          10        1907       kikhi       3         0     0        0     3
24          10        1907       odyuo       3         0     0        0     3
25          10        1907      pienyu       3         0     0        0     3
26          10        1908  yimchunger       3         0     0        0     3
27          10        1909      assumi       3         0     0        0     3
28          10        1909         aye       3         0     0        0     3
29          10        1909       ayemi       3         0     0        0     3
...        ...         ...         ...     ...       ...   ...      ...   ...
1725832     18        2011       rajak       6         0     0        6     0
1725833     18        2011         roy      18         0     6       12     0
1725834     18        2011        sahu       3         0     0        3     0
1725835     18        2011       sajal       3         0     0        3     0
1725836     18        2011         sam       3         0     0        3     0
1725837     18        2011      samant       3         0     0        3     0
1725838     18        2011     samanta       3         0     0        3     0
1725839     18        2011        sana       6         0     0        6     0
1725840     18        2011      santar       6         0     0        6     0
1725841     18        2011      santra       6         0     6        0     0
1725842     18        2011      sardar       6         6     0        6     6
1725843     18        2011       saren       6         0     0        0     6
1725844     18        2011      sarkar      15         3    15        3     0
1725845     18        2011         sau       0         3     0        3     0
1725846     18        2011        sekh       3         0     0        3     0
1725847     18        2011        shau       3         0     3        0     0
1725848     18        2011       shekh       6         0     0        6     0
1725849     18        2011     siddika       0         6     0        6     0
1725850     18        2011        sing       0        12     0        0    12
1725851     18        2011       singh       6         0     0        6     0
1725852     18        2011      sorkar       6         0     0        6     0
1725853     18        2011      sufian       6         0     0        6     0
1725854     18        2011     sultana       0         6     0        6     0
1725855     18        2011       surin       3         0     0        3     0
1725856     18        2011       tanti       0         6     0        6     0
1725857     18        2011    tarafdar       6         0     6        0     0
1725858     18        2011     thakuri       3         0     0        3     0
1725859     18        2011       topno       3         0     0        3     0
1725860     18        2011        tudu       0         3     0        0     3
1725861     18        2011       xalxo       3         0     0        3     0

[1725862 rows x 8 columns]

In [17]:
gdf.to_csv('/opt/data/secc/secc_state10_18_year_ln_outkast.csv.gz', index=False, compression='gzip')

In [18]:
bdf = gdf.groupby(['last_name']).agg({'n_sc': 'sum', 'n_other': 'sum', 'n_st': 'sum', 'n_male': 'sum', 'n_female': 'sum'}).reset_index()
bdf

         last_name   n_sc  n_female    n_st   n_male  n_other
0            aabad   12.0       6.0     0.0    342.0    336.0
1          aabdeen    0.0       3.0     0.0    186.0    189.0
2           aabdin    0.0       0.0     0.0    195.0    195.0
3            aabid    0.0      12.0     0.0    546.0    558.0
4          aachari    6.0      66.0     0.0    522.0    582.0
5          aachary    3.0      51.0     0.0    558.0    606.0
6         aacharya    6.0      33.0     0.0    486.0    513.0
7             aada    3.0       6.0    69.0    102.0     36.0
8           aadhar  414.0      27.0    15.0   1245.0    843.0
9            aadhi   57.0       9.0     0.0    105.0     57.0
10     aadhimoolam  120.0      78.0     0.0    354.0    312.0
11      aadhimulam   66.0      24.0     3.0    183.0    138.0
12           aadil    6.0       3.0     0.0    198.0    195.0
13        aadivasi  225.0      12.0    78.0    345.0     54.0
14           aadok   36.0      18.0     0.0    114.0     96.0
15         aahamad    0.0       6.0     0.0    192.0    198.0
16          aahari    0.0       3.0   246.0    246.0      3.0
17           aahir  120.0      45.0     0.0    228.0    153.0
18          aahmad    6.0       6.0     0.0    363.0    363.0
19           aajad   57.0       0.0     3.0    393.0    333.0
20           aajam    9.0       9.0     0.0    603.0    603.0
21           aakil    0.0       0.0     0.0    483.0    483.0
22           aalam   99.0     105.0     6.0  11532.0  11532.0
23           aalan   96.0      48.0     3.0    219.0    168.0
24            aali   69.0      27.0     6.0   1686.0   1638.0
25           aalim    3.0       6.0     0.0    417.0    420.0
26            aalm    9.0       6.0     0.0    519.0    516.0
27          aalvar   60.0       9.0     0.0    126.0     75.0
28          aameen    3.0       0.0     0.0    132.0    129.0
29          aameta    0.0      33.0     0.0    510.0    543.0
...            ...    ...       ...     ...      ...      ...
32193       zaleel    6.0       0.0     0.0    177.0    171.0
32194        zalil    9.0       6.0     0.0    726.0    723.0
32195         zama    0.0       3.0     0.0    261.0    264.0
32196      zamadar   78.0      36.0     0.0    474.0    432.0
32197        zamal    3.0       6.0     0.0   1293.0   1296.0
32198   zamaluddin    0.0       0.0     0.0    480.0    480.0
32199        zaman    0.0       3.0     0.0    975.0    978.0
32200       zameel    0.0       0.0     0.0    333.0    333.0
32201        zamil    6.0       3.0     3.0    540.0    534.0
32202        zamir    3.0       0.0     0.0    237.0    234.0
32203   zamiruddin    0.0       0.0     0.0    159.0    159.0
32204      zamirul    0.0       0.0     0.0    108.0    108.0
32205          zan   12.0       9.0     3.0    327.0    321.0
32206          zao    0.0      12.0   108.0     96.0      0.0
32207   zasimuddin    0.0       0.0     0.0    144.0    144.0
32208        zaved    0.0       0.0     0.0    216.0    216.0
32209      zeliang    0.0       9.0   126.0    120.0      3.0
32210        zhimo    0.0     291.0  2562.0   2271.0      0.0
32211      zhimomi    0.0      81.0   870.0    789.0      0.0
32212       zholia    0.0      57.0   249.0    192.0      0.0
32213       zhotso    0.0      48.0   255.0    207.0      0.0
32214      zikriya    0.0       0.0     0.0    234.0    234.0
32215       zilani    0.0       0.0     0.0    123.0    123.0
32216      ziyarul    0.0       0.0     0.0    162.0    162.0
32217         zoha    0.0       0.0     0.0    120.0    120.0
32218       zubair    0.0       6.0     0.0    129.0    135.0
32219        zuber    0.0       0.0     0.0    117.0    117.0
32220     zulfikar    0.0       0.0     0.0    102.0    102.0
32221         zumu    0.0      15.0   129.0    114.0      0.0
32222        zutso    0.0      42.0   129.0     87.0      0.0

[32223 rows x 6 columns]